### PR TITLE
Healthy Format Changes

### PR DESCRIPTION
**Pull request by CJMustard1452**
basic structural changes to better follow healthy format structures

### CODE REVIEW

**Comment by NewcoolboysX** [comment]
[ℹ️] Preparing test 1…
[⚠️] Running test 1…
[✅] test 1 has passed all checks

This Pull-Request is ready to be merged to the main branch of this github repository!

**Comment by didntpot** [comment]
both formats make me puke

**Comment by CJMustard1452** [comment]
> both formats make me puke

much agreed !

**Comment by xSuperr** [comment]
I think due to the complexity of this plugin, we must be very cautious when messing with the format. Has this PR been tested? If not vigorous testing must be implied otherwise Wraith0x10 might have some troubles squashing any bugs that may arrise.

- xSuper, PocketMineMP Software Engineer

**Comment by CJMustard1452** [comment]
> I think due to the complexity of this plugin, we must be very cautious when messing with the format. Has this PR been tested? If not vigorous testing must be implied otherwise Wraith0x10 might have some troubles squashing any bugs that may arrise.
> 
> * xSuper, PocketMineMP Software Engineer

I understand the upmost severity of this pull request, and I can confirm I have tested it numerous times.

**Comment by Notsoraalex** [comment]
> basic structural changes to better follow healthy format structures

hey dude i totally agree

**Review by Notsoraalex — COMMENTED** [review]
Hey I notice the $resourcePackID = $resourcePack->getPackId(); does not include a fix to pocketmine forcing default crit particles

**Comment by CJMustard1452** [comment]
> Hey I notice the $resourcePackID = $resourcePack->getPackId(); does not include a fix to pocketmine forcing default crit particles

Thank you for the feedback and observations on the Wraiths resource pack remover project. I appreciate the time you took to review my initial submission. I wanted to take a moment to address the issues raised and outline how I plan to tackle these changes later today.

1. Understanding the Feedback:
Firstly, I have thoroughly reviewed all the feedback provided. I understand the concerns and the specific areas that require improvement. It's crucial for me to ensure that I address each issue comprehensively. I will carefully re-examine the sections where the feedback indicated potential problems or areas for enhancement.

2. Detailed Plan for Fixing Issues:
I will be implementing the following steps to address the feedback:

Code Refactoring: I will start by refactoring the sections of the code that were identified as problematic. This includes optimizing the logic and ensuring that the code adheres to best practices. I’ll focus on improving readability and performance based on the suggestions provided.

Testing and Validation: Next, I will conduct extensive testing to ensure that all the changes are functioning as intended. This will involve creating test cases that cover various scenarios to verify that the resource pack remover works correctly in different situations. I will also check for any potential side effects or regressions that might arise from the recent changes.

Documentation Updates: Based on the feedback, I will update the documentation to reflect any new changes or enhancements made to the resource pack remover. This will include clarifying any instructions or notes that were previously unclear and ensuring that the documentation is accurate and comprehensive.

Addressing Specific Issues: For any specific issues mentioned, I will apply targeted fixes. For example, if there were concerns about particular functionalities or integration aspects, I will address those directly and verify that the fixes resolve the problems effectively.

3. Progress Tracking and Reporting:
To ensure that I stay on track, I will document each step of the process. This includes noting any challenges encountered and how they were addressed. I will also keep a record of the changes made and the results of the testing phase. This documentation will help in providing a clear overview of the progress and will be useful for future reference.

4. Follow-Up and Final Review:
After implementing the changes and completing the testing phase, I will schedule a follow-up review to assess the effectiveness of the fixes. I will then prepare a final report summarizing the changes made, the issues addressed, and any additional observations. This report will be included in the updated Pull Request for your review.

I am committed to ensuring that the Wraiths resource pack remover meets the highest standards and functions seamlessly. Thank you once again for your feedback and for helping me improve the project. I will make the necessary changes and updates later today and will update this Pull Request accordingly.

If there are any further suggestions or if additional feedback arises during this process, please feel free to let me know. I am eager to ensure that all concerns are addressed and that the final version of the resource pack remover meets your expectations.

Best regards,

CJMustard1452

**Comment by CJMustard1452** [comment]
@Wraith0x10 I hope you know this will remain on your page until you make an action

**Comment by didntpot** [comment]
shut the fuck up you're spamming my emails

**Comment by NewcoolboysX** [comment]
> shut the fuck up you're spamming my emails

nah imma do my own thing

**Comment by CJMustard1452** [comment]
pls accept

**Comment by CJMustard1452** [comment]
you can't ignore me forever

**Comment by Wraith0x10** [comment]
shut up

**Pull request merged**
